##This module is developed by Prof. Shin-Pon JU at NSYSU on March 28 2021
package elements; 

use strict;
use warnings;

our (%element); # density (g/cm3), arrangement, mass
#the following are generated by ChatGPT

$element{"H"} = [0.0899, "hcp", 1.00794];

$element{"He"} = [0.1785, "hcp", 4.00260];

$element{"Li"} = [0.534, "bcc", 6.941];

$element{"Be"} = [1.848, "hcp", 9.01218];

$element{"B"} = [2.46, "rhombohedral", 10.81];

$element{"C"} = [2.267, "hexagonal", 12.0107];

$element{"N"} = [0.001251, "hexagonal", 14.00674];

$element{"O"} = [0.001429, "cubic", 15.9994];

$element{"F"} = [0.001696, "cubic", 18.99840];

$element{"Ne"} = [0.0008999, "fcc", 20.1797];

$element{"Na"} = [0.971, "bcc", 22.98977];

$element{"Mg"} = [1.738, "hcp", 24.305];

$element{"Al"} = [2.7,"fcc",26.981539];

$element{"Si"} = [2.3296, "diamond cubic", 28.0855];

$element{"P"} = [1.82, "simple cubic", 30.97376];

$element{"S"} = [2.067, "orthorhombic", 32.06];

$element{"Cl"} = [0.003214, "orthorhombic", 35.45];

$element{"Ar"} = [0.001784, "fcc", 39.948];

$element{"K"} = [0.856, "bcc", 39.0983];

$element{"Ca"} = [1.54, "fcc", 40.078];

$element{"Sc"} = [2.985, "hcp", 44.95591];

$element{"Ti"} = [4.507, "hcp", 47.867];

$element{"V"} = [6.11, "bcc", 50.9415];

$element{"Cr"} = [7.19, "bcc", 52.00];

$element{"Mn"} = [7.21, "bcc", 54.93805];

$element{"Fe"} = [7.874, "bcc", 55.845];

$element{"Co"} = [8.9, "hcp", 58.93319];

$element{"Ni"} = [8.908, "fcc", 58.6934];

$element{"Cu"} = [8.96, "fcc", 63.546];

$element{"Zn"} = [7.134, "hcp", 65.38];

$element{"Ga"} = [5.91, "orthorhombic", 69.723];

$element{"Ge"} = [5.323, "diamond cubic", 72.630];

$element{"As"} = [5.727, "rhombohedral", 74.9216];

$element{"Se"} = [4.81, "hexagonal", 78.96];

$element{"Br"} = [7.59, "orthorhombic", 79.904];

$element{"Kr"} = [0.003733, "fcc", 83.798];

$element{"Rb"} = [1.532, "bcc", 85.4678];

$element{"Sr"} = [2.63, "fcc", 87.62];

$element{"Y"} = [4.469, "hcp", 88.90585];

$element{"Zr"} = [6.506, "hcp", 91.224];

$element{"Nb"} = [8.57, "bcc", 92.90638];

$element{"Mo"} = [10.22, "bcc", 95.94];

$element{"Tc"} = [11.5, "hcp", 98.00];

$element{"Ru"} = [12.37, "hexagonal", 101.07];

$element{"Rh"} = [12.41, "fcc", 102.90550];

$element{"Pd"} = [12.02, "fcc", 106.42];

$element{"Ag"} = [10.49, "fcc", 107.87];

$element{"Cd"} = [8.65, "hcp", 112.41];

$element{"In"} = [7.31, "tetragonal", 114.82];

$element{"Sn"} = [7.287, "diamond cubic", 118.710];

$element{"Sb"} = [6.691, "rhombohedral", 121.760];

$element{"Te"} = [6.24, "hexagonal", 127.60];

$element{"I"} = [4.93, "orthorhombic", 126.90447];

$element{"Xe"} = [0.005887, "fcc", 131.29];

$element{"Cs"} = [1.873, "bcc", 132.90545196];

$element{"Ba"} = [3.594, "bcc", 137.327];

$element{"La"} = [6.145, "hcp", 138.90547];

$element{"Ce"} = [6.77, "fcc", 140.116];

$element{"Pr"} = [6.77, "hcp", 140.90766];

$element{"Nd"} = [7.01, "hcp", 144.242];

$element{"Pm"} = [7.26, "hcp", 145.0];

$element{"Sm"} = [7.52, "hcp", 150.36];

$element{"Eu"} = [5.243, "bcc", 151.964];

$element{"Gd"} = [7.895, "hcp", 157.25];

$element{"Tb"} = [8.229, "hcp", 158.92535];

$element{"Dy"} = [8.55, "hcp", 162.500];

$element{"Ho"} = [8.795, "hcp", 164.93033];

$element{"Er"} = [9.066, "hcp", 167.259];

$element{"Tm"} = [9.321, "hcp", 168.93422];

$element{"Yb"} = [6.965, "fcc", 173.054];

$element{"Lu"} = [9.84, "hcp", 174.9668];

$element{"Hf"} = [13.31, "hcp", 178.49];

$element{"Ta"} = [16.654, "bcc", 180.94788];

$element{"W"} = [19.25, "bcc", 183.84];

$element{"Re"} = [21.02, "hexagonal", 186.207];

$element{"Os"} = [22.59, "hexagonal", 190.23];

$element{"Ir"} = [22.42, "fcc", 192.217];

$element{"Pt"} = [21.45, "fcc", 195.08];

$element{"Au"} = [19.32, "fcc", 196.966569];

$element{"Hg"} = [13.5336, "liquid", 200.592];

$element{"Tl"} = [11.85, "hcp", 204.38];

$element{"Pb"} = [11.342, "fcc", 207.2];

$element{"Bi"} = [9.807, "rhombohedral", 208.98040];

$element{"Th"} = [11.72, "fcc", 232.0377];

$element{"Pa"} = [15.37, "orthorhombic", 231.03588];

$element{"U"} = [18.95, "orthorhombic", 238.02891];

$element{"Np"} = [20.45, "orthorhombic", 237.0];

$element{"Pu"} = [19.84, "monoclinic", 244.0642];

$element{"Am"} = [13.67, "hexagonal", 243.0614];

$element{"Cm"} = [13.51, "hexagonal", 247.0703];

$element{"Bk"} = [14.0, "monoclinic", 247.0703];

$element{"Cf"} = [10.97, "double hexagonal close-packed", 251.0796];

$element{"Es"} = [10.584, "fcc", 252.083];

#$element{"Fm"} = [Unknown, Unknown, 257.0951];
#
#$element{"Md"} = [Unknown, Unknown, 258.0986];
#
#$element{"No"} = [Unknown, Unknown, 259.101];
#
#$element{"Lr"} = [Unknown, Unknown, 262.11];

sub eleObj {# return properties of an element
    my $elem = shift @_;
   # print "\$elem: $elem\n";
   # print @{$element{"$elem"}}."\n";
   # print $element{"$elem"}->[0]."\n";
   # print $element{"$elem"}->[1]."\n";
   # print $element{"$elem"}->[2]."\n";
    return (@{$element{"$elem"}});
}

1;               # Loaded successfully
